# Site settings
baseurl = "https://arhen.dev/"
languageCode = "en"
title = "Arhen Personal Web"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

[params]
	author = "arhen"
	description = "This is Arhen Personal Website, known as Rahmat H Slamet."
	bio = "An engineer who likes to solve problems, and learn new things. Quickly adapt both individually or teams. Specifically very much in love with Linux and Web Technology. My technical skill is around Web Planning then Development using PHP Native/Framework and C# Asp.Net Core. "

	twitter = "arhen_desu"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "arhen"


	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false


	enableGoogleAnalytics = true

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	twitter-square = "https://www.twitter.com/arhen_desu"
	github-square = "https://www.github.com/arhen"
